blank_issues_enabled: false
contact_links:
  - name: Feature request
    url: https://github.com/Praveen-kumar625/MediCare-Management-System-/issues/new
    about: Submit a proposal for a new feature
  - name: Discussions
    url: https://github.com/Praveen-kumar625/MediCare-Management-System-/discussions
    about: Please ask and answer questions here.
